package com.quashbugs.quash.dto.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SignUpRequestDTO {


    private String username;
    private String workEmail;
    private String password;
    private String profileImage;
    private String coverImage;
    private String signUpType;
    // You can omit fields like emailVerified, verificationToken, and createdAt
    // as they might be handled by the backend during registration.

    // Constructors, getters, and setters can be generated by Lombok annotations.
    public SignUpRequestDTO(String workEmail, String password){
        this.workEmail = workEmail;
        this.password = password;
    }
}
